server:
  port: 4572

spring:
  application:
    name: courses
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password: kam1z1la
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351